name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted   # ← le changement clé
    steps:
      - name: Pull latest code
        run: |
          cd /var/www/applications_gestion
          git fetch origin main
          git reset --hard origin/main